baseURL = "/"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
languageCode = "en-US"
metaDataFormat = "yaml"
paginate = 25

[outputs]
home = ["HTML", "RSS","JSON"]

[params]
brand = "Revenue Health"
description = "Revenue Health"

[permalinks]
post = "/post/:year/:month/:day/:slug/"
